
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Trips', [{
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr',
      departure_time: '9:00am',
      arrival_time: '1:00pm',
      travel_date_begin: 'Wed 2/26',
      travel_date_end: 'Wed 2/26',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '11:00am',
      arrival_time: '3:00pm',
      travel_date_begin: 'Wed 2/26',
      travel_date_end: 'Wed 2/26',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '1:00pm',
      arrival_time: '5:00pm',
      travel_date_begin: 'Wed 2/26',
      travel_date_end: 'Wed 2/26',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '3:00pm',
      arrival_time: '7:00pm',
      travel_date_begin: 'Wed 2/26',
      travel_date_end: 'Wed 2/26',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '6:00pm',
      arrival_time: '10:00pm',
      travel_date_begin: 'Wed 2/26',
      travel_date_end: 'Wed 2/26',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr',
      departure_time: '9:00am',
      arrival_time: '1:00pm',
      travel_date_begin: 'Thurs 2/27',
      travel_date_end: 'Thurs 2/27',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '11:00am',
      arrival_time: '3:00pm',
      travel_date_begin: 'Thurs 2/27',
      travel_date_end: 'Thurs 2/27',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '1:00pm',
      arrival_time: '5:00pm',
      travel_date_begin: 'Thurs 2/27',
      travel_date_end: 'Thurs 2/27',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '3:00pm',
      arrival_time: '7:00pm',
      travel_date_begin: 'Thurs 2/27',
      travel_date_end: 'Thurs 2/27',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '6:00pm',
      arrival_time: '10:00pm',
      travel_date_begin: 'Thurs 2/27',
      travel_date_end: 'Thurs 2/27',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr',
      departure_time: '9:00am',
      arrival_time: '1:00pm',
      travel_date_begin: 'Fri 2/28',
      travel_date_end: 'Fri 2/28',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '11:00am',
      arrival_time: '3:00pm',
      travel_date_begin: 'Fri 2/28',
      travel_date_end: 'Fri 2/28',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '1:00pm',
      arrival_time: '5:00pm',
      travel_date_begin: 'Fri 2/28',
      travel_date_end: 'Fri 2/28',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '3:00pm',
      arrival_time: '7:00pm',
      travel_date_begin: 'Fri 2/28',
      travel_date_end: 'Fri 2/28',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '6:00pm',
      arrival_time: '10:00pm',
      travel_date_begin: 'Fri 2/28',
      travel_date_end: 'Fri 2/28',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr',
      departure_time: '9:00am',
      arrival_time: '1:00pm',
      travel_date_begin: 'Sat 2/29',
      travel_date_end: 'Sat 2/29',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '11:00am',
      arrival_time: '3:00pm',
      travel_date_begin: 'Sat 2/29',
      travel_date_end: 'Sat 2/29',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '1:00pm',
      arrival_time: '5:00pm',
      travel_date_begin: 'Sat 2/29',
      travel_date_end: 'Sat 2/29',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '3:00pm',
      arrival_time: '7:00pm',
      travel_date_begin: 'Sat 2/29',
      travel_date_end: 'Sat 2/29',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '6:00pm',
      arrival_time: '10:00pm',
      travel_date_begin: 'Sat 2/29',
      travel_date_end: 'Sat 2/29',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr',
      departure_time: '9:00am',
      arrival_time: '1:00pm',
      travel_date_begin: 'Sun 3/1',
      travel_date_end: 'Sun 3/1',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '11:00am',
      arrival_time: '3:00pm',
      travel_date_begin: 'Sun 3/1',
      travel_date_end: 'Sun 3/1',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '1:00pm',
      arrival_time: '5:00pm',
      travel_date_begin: 'Sun 3/1',
      travel_date_end: 'Sun 3/1',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '3:00pm',
      arrival_time: '7:00pm',
      travel_date_begin: 'Sun 3/1',
      travel_date_end: 'Sun 3/1',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '6:00pm',
      arrival_time: '10:00pm',
      travel_date_begin: 'Sun 3/1',
      travel_date_end: 'Sun 3/1',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr',
      departure_time: '9:00am',
      arrival_time: '1:00pm',
      travel_date_begin: 'Mon 3/2',
      travel_date_end: 'Mon 3/2',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '11:00am',
      arrival_time: '3:00pm',
      travel_date_begin: 'Mon 3/2',
      travel_date_end: 'Mon 3/2',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '1:00pm',
      arrival_time: '5:00pm',
      travel_date_begin: 'Mon 3/2',
      travel_date_end: 'Mon 3/2',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '3:00pm',
      arrival_time: '7:00pm',
      travel_date_begin: 'Mon 3/2',
      travel_date_end: 'Mon 3/2',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '6:00pm',
      arrival_time: '10:00pm',
      travel_date_begin: 'Mon 3/2',
      travel_date_end: 'Mon 3/2',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr',
      departure_time: '9:00am',
      arrival_time: '1:00pm',
      travel_date_begin: 'Tue 3/3',
      travel_date_end: 'Tue 3/3',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '11:00am',
      arrival_time: '3:00pm',
      travel_date_begin: 'Tue 3/3',
      travel_date_end: 'Tue 3/3',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '1:00pm',
      arrival_time: '5:00pm',
      travel_date_begin: 'Tue 3/3',
      travel_date_end: 'Tue 3/3',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '3:00pm',
      arrival_time: '7:00pm',
      travel_date_begin: 'Tue 3/3',
      travel_date_end: 'Tue 3/3',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '6:00pm',
      arrival_time: '10:00pm',
      travel_date_begin: 'Tue 3/3',
      travel_date_end: 'Tue 3/3',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr',
      departure_time: '9:00am',
      arrival_time: '1:00pm',
      travel_date_begin: 'Wed 3/4',
      travel_date_end: 'Wed 3/4',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '11:00am',
      arrival_time: '3:00pm',
      travel_date_begin: 'Wed 3/4',
      travel_date_end: 'Wed 3/4',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '1:00pm',
      arrival_time: '5:00pm',
      travel_date_begin: 'Wed 3/4',
      travel_date_end: 'Wed 3/4',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '3:00pm',
      arrival_time: '7:00pm',
      travel_date_begin: 'Wed 3/4',
      travel_date_end: 'Wed 3/4',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '6:00pm',
      arrival_time: '10:00pm',
      travel_date_begin: 'Wed 3/4',
      travel_date_end: 'Wed 3/4',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr',
      departure_time: '9:00am',
      arrival_time: '1:00pm',
      travel_date_begin: 'Thurs 3/5',
      travel_date_end: 'Thurs 3/5',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '11:00am',
      arrival_time: '3:00pm',
      travel_date_begin: 'Thurs 3/5',
      travel_date_end: 'Thurs 3/5',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '1:00pm',
      arrival_time: '5:00pm',
      travel_date_begin: 'Thurs 3/5',
      travel_date_end: 'Thurs 3/5',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '3:00pm',
      arrival_time: '7:00pm',
      travel_date_begin: 'Thurs 3/5',
      travel_date_end: 'Thurs 3/5',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '6:00pm',
      arrival_time: '10:00pm',
      travel_date_begin: 'Thurs 3/5',
      travel_date_end: 'Thurs 3/5',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr',
      departure_time: '9:00am',
      arrival_time: '1:00pm',
      travel_date_begin: 'Fri 3/6',
      travel_date_end: 'Fri 3/6',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '11:00am',
      arrival_time: '3:00pm',
      travel_date_begin: 'Fri 3/6',
      travel_date_end: 'Fri 3/6',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '1:00pm',
      arrival_time: '5:00pm',
      travel_date_begin: 'Fri 3/6',
      travel_date_end: 'Fri 3/6',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '3:00pm',
      arrival_time: '7:00pm',
      travel_date_begin: 'Fri 3/6',
      travel_date_end: 'Fri 3/6',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '6:00pm',
      arrival_time: '10:00pm',
      travel_date_begin: 'Fri 3/6',
      travel_date_end: 'Fri 3/6',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr',
      departure_time: '9:00am',
      arrival_time: '1:00pm',
      travel_date_begin: 'Sat 3/7',
      travel_date_end: 'Sat 3/7',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '11:00am',
      arrival_time: '3:00pm',
      travel_date_begin: 'Sat 3/7',
      travel_date_end: 'Sat 3/7',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '1:00pm',
      arrival_time: '5:00pm',
      travel_date_begin: 'Sat 3/7',
      travel_date_end: 'Sat 3/7',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '3:00pm',
      arrival_time: '7:00pm',
      travel_date_begin: 'Sat 3/7',
      travel_date_end: 'Sat 3/7',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'NYC',
      travel_time: '4 hr,
      departure_time: '6:00pm',
      arrival_time: '10:00pm',
      travel_date_begin: 'Sat 3/7',
      travel_date_end: 'Sat 3/7',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.006,
      arrival_latt: 40.7128,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '9:00am',
      arrival_time: '10:30am',
      travel_date_begin: 'Wed 2/26',
      travel_date_end: 'Wed 2/26',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '11:00am',
      arrival_time: '12:30pm',
      travel_date_begin: 'Wed 2/26',
      travel_date_end: 'Wed 2/26',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '1:00pm',
      arrival_time: '2:30pm',
      travel_date_begin: 'Wed 2/26',
      travel_date_end: 'Wed 2/26',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '4:00pm',
      arrival_time: '5:30pm',
      travel_date_begin: 'Wed 2/26',
      travel_date_end: 'Wed 2/26',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '6:00pm',
      arrival_time: '7:30pm',
      travel_date_begin: 'Wed 2/26',
      travel_date_end: 'Wed 2/26',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '9:00am',
      arrival_time: '10:30am',
      travel_date_begin: 'Thurs 2/27',
      travel_date_end: 'Thurs 2/27',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '11:00am',
      arrival_time: '12:30pm',
      travel_date_begin: 'Thurs 2/27',
      travel_date_end: 'Thurs 2/27',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '1:00pm',
      arrival_time: '2:30pm',
      travel_date_begin: 'Thurs 2/27',
      travel_date_end: 'Thurs 2/27',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '4:00pm',
      arrival_time: '5:30pm',
      travel_date_begin: 'Thurs 2/27',
      travel_date_end: 'Thurs 2/27',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '6:00pm',
      arrival_time: '7:30pm',
      travel_date_begin: 'Thurs 2/27',
      travel_date_end: 'Thurs 2/27',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '9:00am',
      arrival_time: '10:30am',
      travel_date_begin: 'Fri 2/28',
      travel_date_end: 'Fri 2/28',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '11:00am',
      arrival_time: '12:30pm',
      travel_date_begin: 'Fri 2/28',
      travel_date_end: 'Fri 2/28',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '1:00pm',
      arrival_time: '2:30pm',
      travel_date_begin: 'Fri 2/28',
      travel_date_end: 'Fri 2/28',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '4:00pm',
      arrival_time: '5:30pm',
      travel_date_begin: 'Fri 2/28',
      travel_date_end: 'Fri 2/28',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '6:00pm',
      arrival_time: '7:30pm',
      travel_date_begin: 'Fri 2/28',
      travel_date_end: 'Fri 2/28',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '9:00am',
      arrival_time: '10:30am',
      travel_date_begin: 'Sat 2/29',
      travel_date_end: 'Sat 2/29',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '11:00am',
      arrival_time: '12:30pm',
      travel_date_begin: 'Sat 2/29',
      travel_date_end: 'Sat 2/29',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '1:00pm',
      arrival_time: '2:30pm',
      travel_date_begin: 'Sat 2/29',
      travel_date_end: 'Sat 2/29',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '4:00pm',
      arrival_time: '5:30pm',
      travel_date_begin: 'Sat 2/29',
      travel_date_end: 'Sat 2/29',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '6:00pm',
      arrival_time: '7:30pm',
      travel_date_begin: 'Sat 2/29',
      travel_date_end: 'Sat 2/29',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '9:00am',
      arrival_time: '10:30am',
      travel_date_begin: 'Sun 3/1',
      travel_date_end: 'Sun 3/1',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '11:00am',
      arrival_time: '12:30pm',
      travel_date_begin: 'Sun 3/1',
      travel_date_end: 'Sun 3/1',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '1:00pm',
      arrival_time: '2:30pm',
      travel_date_begin: 'Sun 3/1',
      travel_date_end: 'Sun 3/1',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '4:00pm',
      arrival_time: '5:30pm',
      travel_date_begin: 'Sun 3/1',
      travel_date_end: 'Sun 3/1',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '6:00pm',
      arrival_time: '7:30pm',
      travel_date_begin: 'Sun 3/1',
      travel_date_end: 'Sun 3/1',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '9:00am',
      arrival_time: '10:30am',
      travel_date_begin: 'Mon 3/2',
      travel_date_end: 'Mon 3/2',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '11:00am',
      arrival_time: '12:30pm',
      travel_date_begin: 'Mon 3/2',
      travel_date_end: 'Mon 3/2',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '1:00pm',
      arrival_time: '2:30pm',
      travel_date_begin: 'Mon 3/2',
      travel_date_end: 'Mon 3/2',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '4:00pm',
      arrival_time: '5:30pm',
      travel_date_begin: 'Mon 3/2',
      travel_date_end: 'Mon 3/2',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '6:00pm',
      arrival_time: '7:30pm',
      travel_date_begin: 'Mon 3/2',
      travel_date_end: 'Mon 3/2',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '9:00am',
      arrival_time: '10:30am',
      travel_date_begin: 'Tue 3/3',
      travel_date_end: 'Tue 3/3',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '11:00am',
      arrival_time: '12:30pm',
      travel_date_begin: 'Tue 3/3',
      travel_date_end: 'Tue 3/3',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '1:00pm',
      arrival_time: '2:30pm',
      travel_date_begin: 'Tue 3/3',
      travel_date_end: 'Tue 3/3',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '4:00pm',
      arrival_time: '5:30pm',
      travel_date_begin: 'Tue 3/3',
      travel_date_end: 'Tue 3/3',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '6:00pm',
      arrival_time: '7:30pm',
      travel_date_begin: 'Tue 3/3',
      travel_date_end: 'Tue 3/3',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '9:00am',
      arrival_time: '10:30am',
      travel_date_begin: 'Wed 3/4',
      travel_date_end: 'Wed 3/4',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '11:00am',
      arrival_time: '12:30pm',
      travel_date_begin: 'Wed 3/4',
      travel_date_end: 'Wed 3/4',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '1:00pm',
      arrival_time: '2:30pm',
      travel_date_begin: 'Wed 3/4',
      travel_date_end: 'Wed 3/4',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '4:00pm',
      arrival_time: '5:30pm',
      travel_date_begin: 'Wed 3/4',
      travel_date_end: 'Wed 3/4',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '6:00pm',
      arrival_time: '7:30pm',
      travel_date_begin: 'Wed 3/4',
      travel_date_end: 'Wed 3/4',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '9:00am',
      arrival_time: '10:30am',
      travel_date_begin: 'Thurs 3/5',
      travel_date_end: 'Thurs 3/5',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '11:00am',
      arrival_time: '12:30pm',
      travel_date_begin: 'Thurs 3/5',
      travel_date_end: 'Thurs 3/5',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '1:00pm',
      arrival_time: '2:30pm',
      travel_date_begin: 'Thurs 3/5',
      travel_date_end: 'Thurs 3/5',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '4:00pm',
      arrival_time: '5:30pm',
      travel_date_begin: 'Thurs 3/5',
      travel_date_end: 'Thurs 3/5',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '6:00pm',
      arrival_time: '7:30pm',
      travel_date_begin: 'Thurs 3/5',
      travel_date_end: 'Thurs 3/5',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '9:00am',
      arrival_time: '10:30am',
      travel_date_begin: 'Fri 3/6',
      travel_date_end: 'Fri 3/6',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '11:00am',
      arrival_time: '12:30pm',
      travel_date_begin: 'Fri 3/6',
      travel_date_end: 'Fri 3/6',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '1:00pm',
      arrival_time: '2:30pm',
      travel_date_begin: 'Fri 3/6',
      travel_date_end: 'Fri 3/6',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '4:00pm',
      arrival_time: '5:30pm',
      travel_date_begin: 'Fri 3/6',
      travel_date_end: 'Fri 3/6',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '6:00pm',
      arrival_time: '7:30pm',
      travel_date_begin: 'Fri 3/6',
      travel_date_end: 'Fri 3/6',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '9:00am',
      arrival_time: '10:30am',
      travel_date_begin: 'Sat 3/7',
      travel_date_end: 'Sat 3/7',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '11:00am',
      arrival_time: '12:30pm',
      travel_date_begin: 'Sat 3/7',
      travel_date_end: 'Sat 3/7',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '1:00pm',
      arrival_time: '2:30pm',
      travel_date_begin: 'Sat 3/7',
      travel_date_end: 'Sat 3/7',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '4:00pm',
      arrival_time: '5:30pm',
      travel_date_begin: 'Sat 3/7',
      travel_date_end: 'Sat 3/7',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      departure_city: 'Boston',
      destination_city: 'Trenton',
      travel_time: '1 hr 30 min',
      departure_time: '6:00pm',
      arrival_time: '7:30pm',
      travel_date_begin: 'Sat 3/7',
      travel_date_end: 'Sat 3/7',
      paid: true,
      departure_long: -71.0275,
      departure_latt: 42.2352,
      arrival_long: -74.756138,
      arrival_latt: 40.221741,
      createdAt: new Date(),
      updatedAt: new Date()
    }
    ], {});
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Trips', null, {});
  }
};